### ISSUE TITLE
Use multiple TemplatePaths-Feature

### ISSUE THREAD

**Issue by h3nn3s** [Skyfillers/sf_filecollection_gallery#13]
As of compatibility is set to 6.2+ you can use the great multiple template paths feature like EXT:news is using it.

http://docs.typo3.org/typo3cms/extensions/news/Main/Templating/Start/Index.html#changing-paths-of-the-template

Sorry, but I think this is still undocumented in core doc, but it is very simple.
Higher IDs are executed first, lower afterwards.

**Comment by machwatt** [comment]
Made an update to TER including this feature.
