### ISSUE TITLE
Lightbox

### ISSUE THREAD

**Issue by alexingo** [Skyfillers/sf_filecollection_gallery#14]
Hi,

I've installed the extension. I like the simplicity of it. But I've got a problem. The lightbox doesn't work.

...div class="sf-filecollection-gallery-image-container">
	..a rel="{$plugin.tx_sffilecollectiongallery.settings.image.lightbox}" class="{$plugin.tx_sffilecollectiongallery.settings.image.lightbox}" title=""
						   href="...">
	<img src="..." alt="" />
						</a...
</div...

Could you help me please?
Best regards 
alexingo

**Comment by machwatt** [comment]
Hey @alexingo 

Yeah you're right, there is a some issue with that...
I'll fix this and make a new version in TER.

But some further info:
These settings are only to make this "gallery" able to use a lightbox feature. It is not built in (for simplicity and to make it as small as possible), so you need to add another extension to get that done.

For the easiest include of a lightbox, you might use this http://typo3.org/extensions/repository/view/cl_jquery_fancybox  

It needs an rel or class attribute named "lightbox" on the link tag. (Thats the settings.lightbox value by default) So all you need to do then is to include fancyBox1 or fancyBox2 template.

**Comment by machwatt** [comment]
@alexingo You might download the dev branch now ;) if TER is not fast enough for you

**Comment by machwatt** [comment]
Upload to TER in progress

**Comment by alexingo** [comment]
Thanks a lot!
