### ISSUE TITLE
Its not possible to overwrite Pagination Template

### ISSUE THREAD

**Issue by rabe69** [Skyfillers/sf_filecollection_gallery#21]
I tried this TS:
plugin.tx_sffilecollectiongallery.view.widget.SKYFILLERS\SfFilecollectionGallery\ViewHelpers\PaginateViewHelper.templateRootPath = EXT:myextension/Resources/Private/Templates/

And put the modified pagination template file in this folder:
typo3conf/ext/myextension/Resources/Private/Templates/ViewHelpers/Pagination/Index.html

also tried this pathes:
typo3conf/ext/myextension/Resources/Private/Templates/Index.html
typo3conf/ext/myextension/Resources/Private/Templates/Pagination/Index.html
typo3conf/ext/myextension/Resources/Private/Templates/ViewHelpers/Widget/Pagination/Index.html

In every case i got this error in frontend:
Sorry, the requested view was not found.

The technical reason is: No template was found. View could not be resolved for action "index" in class "SKYFILLERS\SfFilecollectionGallery\Controller\PaginateController".

**Comment by rabe69** [comment]
Sorry my fault.
I had an typo in my extension name.

This is working:
plugin.tx_sffilecollectiongallery.view.widget.SKYFILLERS\SfFilecollectionGallery\ViewHelpers\PaginateViewHelper.templateRootPath = EXT:myextension/Resources/Private/Templates/

Put modified pagination template here:
typo3conf/ext/myextension/Resources/Private/Templates/Pagination/Index.html

**Comment by machwatt** [comment]
No problem, happy you are working with it.
