### ISSUE TITLE
Language Settings

### ISSUE THREAD

**Issue by alexingo** [Skyfillers/sf_filecollection_gallery#27]
Hi, what's the best way to set the language? Are there typoscript instructions availabe to set the language for first and last in pagination or should I copy the file settings in locallang.xlf 
<file source-language="de" ... </file>
I've tried to overwrite the english data and to copy, but it didn't work!
Best regards
alexingo

**Comment by machwatt** [comment]
Hi @alexingo ,
you might get some idea how to set the values to your needs here http://docs.typo3.org/typo3cms/ExtbaseFluidBook/9-CrosscuttingConcerns/1-localizing-and-internationalizing-an-extension.html

If you want to use TS for this you might set the values in TypoScript Setup like this:
```
plugin.tx_sffilecollectiongallery._LOCAL_LANG.default.pagination_first
```

**Comment by alexingo** [comment]
Thanks a lot, with TS it worked fine!
Is it possible to insert a diashow?

**Comment by machwatt** [comment]
@alexingo can you open another issue with a more detailed description? If you need a more extended template, you may look at the Readme/Documentation how to use your own template for this extension.
