### ISSUE TITLE
[BUG] Check t3colorbox functionality

### ISSUE THREAD

**Issue by krachtvoll** [Skyfillers/sf_filecollection_gallery#50]
Ich kann die lightbox für die Gallery nicht aktivieren???

Benutzt wird die  t3colorbox welche auch sonst funktioniert.

Unklar ist im Konstanteneditor
- Enable lightbox for default template, hier habe ich: 1
- Choose the lightbox related value (Default 'lightbox'), hier habe ich jetzt t3colorbox

Aber alle Versuche ohne Erfolg.

**Comment by machwatt** [comment]
You need to make the following settings 

    plugin.tx_sffilecollectiongallery.settings {
       lightbox = t3colorbox cboxElement
    }

and check the checkbox for "enableLightbox" in the plugin.
