### ISSUE TITLE
PHP 5.3 compatibility issue

### ISSUE THREAD

**Issue by ArminVieweg** [Skyfillers/sf_filecollection_gallery#52]
Your extension should be compatible with TYPO3 6.2. This is what you've defined in emconf. But TYPO3 6.2 is compatible with PHP down to version 5.3.7.

Unfortunately your extension is not compatible with that PHP version (5.3.x).

Example:
`$this->frontendConfigurationManager->getConfiguration()['settings']['order']`

This causes in frontend this error:
`Parse error: syntax error, unexpected '[' in ...\typo3conf\ext\sf_filecollection_gallery\Classes\Service\FileCollectionService.php on line 175`

To fix it, you need to assign the return value of the method to a variable, and then you are allowed to access the keys of the array. 

I did not check the rest of the extension, but when you perform a search on `)[` you should find all spots, which are incompatible with older php versions.

**Comment by machwatt** [comment]
Thanks for the issue and your pull request. I might find the time to look for other occurences in the code this evening.

**Comment by machwatt** [comment]
Closed by https://github.com/Skyfillers/sf_filecollection_gallery/releases/tag/1.2.1
