### ISSUE TITLE
Image sorting

### ISSUE THREAD

**Issue by stwsimon** [Skyfillers/sf_filecollection_gallery#57]
Any way to add the ability to manually sort the images - not just asc/desc, but in a specific, user defined order.

**Comment by machwatt** [comment]
This ticket is already open in #42 I'll try to implement it this week.

**Comment by stwsimon** [comment]
A manual sort would require some sort of view of the files in the plugin, wouldn't it.  As far as I can see there is no way to manually sort files in the file list.

**Comment by machwatt** [comment]
It is possible to sort the images in the FileCollection

**Comment by machwatt** [comment]
But as written above in #42 it is only possible to sort ASC / DESC not "like in filecollection". But this will be possible with the next release.

**Comment by stwsimon** [comment]
How do you sort a floor collection?  I haven't seen that.

**Comment by machwatt** [comment]
If you add images to the file collection in the TYPO3 backend you can sort them via drag and drop. (As i said above, the current version will ignore this, but the next release will be able to use the sorting from the file collection)

If you are using folder based file collection you need to name the files and sort ascending or descending in the plugin.

**Comment by stwsimon** [comment]
Thank you, I didn't realize that.

**Comment by machwatt** [comment]
:+1: If you need this feature right now, feel free to check out the master branch
